apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
  labels:
    name: tomcat-service
    app: sample-app
spec:
  # type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      # nodePort: 30333
  selector:
    name: tomcat-pod
    app: sample-app
